title: "Front-End Dev Storage"
author: "GoyoungKim"
description: "Really cool blog about ... something"
more: "read more »"
url: "https://pipigoyoung.github.io/"
baseurl: "/storage"
paginate: 2
permalink: pretty
excerpt_separator: "\n\n\n" # two blank lines

style:
  minimalist: true
  dark: true

navigation:
  - index.html
  - archive.html
  - about.md

comments:
  disqus: "disqus-contrast"
#  isso: "comments.mysite.org"

links: # see http://fontawesome.io/icons/#brand for all possible icons
  - twitter: "https://twitter.com/twitter/"
  - github: "https://github.com/niklasbuschmann/contrast"
  - envelope: "mailto:niklas.buschmann@posteo.de"

defaults: [{scope: {path: ""}, values: {layout: "default"}}, {scope: {path: "", type: "posts"}, values: {comments: true}}]
sass: {style: expanded}
plugins: [jekyll-feed, jekyll-paginate]
